<div class="content-wrapper" style="min-height: 946px;">
    <section class="content-header">
        <h1><i class="fa fa-file-text-o"></i> Document Reports</h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <?php $this->load->view('admin/documentreport/_document_reports'); ?>
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-search"></i> Select Criteria</h3>
                    </div>
                    <form action="<?php echo site_url('admin/documentreport/tcreport') ?>" method="post">
                        <?php echo $this->customlib->getCSRF(); ?>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Class</label>
                                        <select autofocus="" id="class_id" name="class_id" class="form-control" >
                                            <option value="">Select</option>
                                            <?php foreach ($classlist as $class) { ?>
                                                <option value="<?php echo $class['id'] ?>" <?php echo set_select('class_id', $class['id'], ($class_id == $class['id'])); ?>><?php echo $class['class'] ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Section</label>
                                        <select id="section_id" name="section_id" class="form-control" >
                                            <option value="">Select</option>
                                            <?php if (isset($section_list)) {
                                                foreach ($section_list as $section) { ?>
                                                    <option value="<?php echo $section['section_id'] ?>" <?php echo set_select('section_id', $section['section_id'], ($section_id == $section['section_id'])); ?>><?php echo $section['section'] ?></option>
                                                <?php }
                                            } ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-4" style="margin-top: 25px;">
                                    <button type="submit" name="search" value="search_filter" class="btn btn-primary btn-sm pull-right"><i class="fa fa-search"></i> Search</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    
                    <div class="box-header ptbnull"></div>
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-file-text-o"></i> TC Report</h3>
                    </div>
                    <div class="box-body table-responsive">
                        <table class="table table-striped table-bordered table-hover example">
                            <thead>
                                <tr>
                                    <th>Admission No</th>
                                    <th>Student Name</th>
                                    <th>Class</th>
                                    <th>TC Template</th>
                                    <th>Generated By</th>
                                    <th>Generated Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (isset($resultlist)) {
                                    foreach ($resultlist as $report) { ?>
                                        <tr>
                                            <td><?php echo $report['admission_no']; ?></td>
                                            <td><?php echo $this->customlib->getFullName($report['firstname'], $report['middlename'], $report['lastname'], $sch_setting->middlename, $sch_setting->lastname); ?></td>
                                            <td><?php echo $report['class'] . " (" . $report['section'] . ")"; ?></td>
                                            <td><?php echo $report['template_name']; ?></td>
                                            <td><?php echo $report['staff_firstname'] . " " . $report['staff_lastname']; ?></td>
                                            <td><?php echo date($this->customlib->getSchoolDateFormat(true), strtotime($report['generated_date'])); ?></td>
                                        </tr>
                                    <?php }
                                } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<script type="text/javascript">
    function getSectionByClass(class_id, section_id) {
        if (class_id != "") {
            $('#section_id').html("");
            var base_url = '<?php echo base_url(); ?>';
            var div_data = '<option value="">Select</option>';
            $.ajax({
                type: "GET",
                url: base_url + "sections/getByClass",
                data: {'class_id': class_id},
                dataType: "json",
                success: function (data) {
                    $.each(data, function (i, obj)
                    {
                        var sel = "";
                        if (section_id == obj.section_id) {
                            sel = "selected";
                        }
                        div_data += "<option value=" + obj.section_id + " " + sel + ">" + obj.section + "</option>";
                    });
                    $('#section_id').append(div_data);
                }
            });
        }
    }

    $(document).ready(function () {
        $(document).on('change', '#class_id', function (e) {
            $('#section_id').html("");
            var class_id = $(this).val();
            getSectionByClass(class_id, 0);
        });
    });
</script>
